services:
  api:
    build: .
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      DB_URI: mongodb://mongo:27017/express_starter
      CORS_ORIGINS: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
